language: go

go:
  - 1.13.x

services:
  - docker

before_install:
- docker pull tarent/loginsrv
- docker run -d -p 8080:8080 tarent/loginsrv -cookie-secure=false -jwt-secret my_secret -simple bob=secret -jwt-refreshes 20
- docker ps -a

script:
- go test -v -count=1 ./...
